Repository retracedhq/retraced, pull requests merged in 2024-04, with the labels that each got.

#1361 chore: Update artifact upload retention to 1 day
  .github/workflows/main.yml
Labels: enhancement

#1381 Handle 400 error from ES
  src/_processor/workers/saveEventToElasticsearch.ts
Labels: bug, bug::normal

#1382 Remove invalid date from target.fields
  src/_processor/workers/saveEventToElasticsearch.ts
Labels: type::bug, bug::normal
